### ISSUE TITLE
How to postpone bus start up?

### ISSUE THREAD

**Issue by Maxwe11** [rebus-org/Rebus.Autofac#9] opened 2017-12-27 20:24 UTC
Hello guys,
One of the common scenario for ASP .NET Core application is registering all dependencies in `ConfigureServices` method and applying DB migrations in `Configure` method in `Startup` class.
In case of using SQL based transport  for messages, database may not exist on the moment of container build up. Why `Rebus.Autofac` decides when to start up the bus?

**Comment by mookid8000** [comment] 2017-12-28 12:58
The Rebus/Autofac integration is made so that it initializes and starts the bus when you call `containerBuilder.Build()`.

If you want to delay the time of when Rebus starts receiving messages, you can initialize it with zero workers

```csharp
.Options(o => {
    o.SetNumberOfWorkers(0);
})
```
and then start receiving messages some time later by calling

```csharp
bus.Advanced.Workers.SetNumberOfWorkers(2);
```

but I am not sure I understand what you are asking about, actually 😐 maybe you can clarify a bit, I am not really accustomed to ASP.NET Core yet....

**Comment by mookid8000** [comment] 2018-01-03 06:41
Hi @Maxwe11 , did you figure it out?

**Comment by Maxwe11** [comment] 2018-01-05 14:18
@mookid8000 I will prepare sample with repro of the problem in a couple of days.

**Comment by almsyx** [comment] 2018-01-19 11:51
Hi @mookid8000 , @Maxwe11 

I'm having the same issue as well. 

We are configuring different services into our container (Eg Database configuration, SQS Configuration, ...  which is required for different services. We also require this database configuration during the rebus configuration (eg for setting the Saga database). 

The problem is that inside the rebus configuration we want to resolve this database configuration from the container, but at that moment we don't have it since the container hasn't been build yet , we are doing this action now ... 

So if possible i would like to be able to start Rebus later iso during container build.

**Comment by mookid8000** [comment] 2018-04-26 06:55
can I close this one?

**Closed** 2018-04-26 06:55 UTC

**Comment by Maxwe11** [comment] 2018-04-30 15:43
Not anymore, `Rebus.ServiceProvider` do the trick.
